[package]
name = "belnapian"
version = "0.1.0"

description = "Belnap's 4-valued logic basic building blocks in Rust"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Coder-Spirit/belnapian"

edition = "2021"

[dependencies]
